### ISSUE TITLE
Error in importing dataset_utils

### ISSUE THREAD

**Issue by Jason3900** [google-research/scenic#1059]
After install the scenic successfully in python3.9 via `pip install .`, I cannot import the dataset_utils with `from scenic.dataset_lib import dataset_utils`. What should I do to fix it?
```
W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/projects/magvit/deps/scenic/scenic/dataset_lib/dataset_utils.py", line 41, in <module>
    class Dataset:
  File "/workspace/projects/magvit/deps/scenic/scenic/dataset_lib/dataset_utils.py", line 71, in Dataset
    train_iter: DatasetIterator | DatasetIteratorProvider | None = None
TypeError: unsupported operand type(s) for |: '_UnionGenericAlias' and '_CallableGenericAlias'
```

**Comment by dohyun1411** [comment]
Did you solve the problem?
