### ISSUE TITLE
Issue of big_vision module during owlv2 fine tuning

### ISSUE THREAD

**Issue by MattLiutt** [google-research/scenic#1068]
When I was working on owlv2 training/fine-tuning, errors occurred below, all work under google colab.
```
!rm -rf *
!rm -rf .config
!rm -rf .git
!git clone https://github.com/google-research/scenic.git .
!python -m pip install -q .
!python -m pip install -r ./scenic/projects/owl_vit/requirements.txt

# Also install big_vision, which is needed for the mask head:
!mkdir /big_vision
!git clone https://github.com/google-research/big_vision.git /big_vision
!python -m pip install -r /big_vision/big_vision/requirements.txt
import sys
sys.path.append('/big_vision/')
!echo "Done."
```
So when I run the [training script](https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit#training), following error pops out.
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/scenic/projects/owl_vit/main.py", line 25, in <module>
    from scenic.projects.owl_vit import models
  File "/content/scenic/projects/owl_vit/models.py", line 25, in <module>
    from scenic.projects.owl_vit import layers
  File "/content/scenic/projects/owl_vit/layers.py", line 22, in <module>
    from big_vision.models import bit
ModuleNotFoundError: No module named 'big_vision'
```
I checked #1043 and #982, and I move big_vision under scenic directory, still got an issue.
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/scenic/projects/owl_vit/main.py", line 25, in <module>
    from scenic.projects.owl_vit import models
  File "/content/scenic/projects/owl_vit/models.py", line 25, in <module>
    from scenic.projects.owl_vit import layers
  File "/content/scenic/projects/owl_vit/layers.py", line 22, in <module>
    from big_vision.models import bit
ModuleNotFoundError: No module named 'big_vision.models'
```
If anyone can help, it would be much appreciated! Thanks!

**Comment by hrtowii** [comment]
I’m also having this exact same issue, does anyone have a solution?

**Comment by salashhab** [comment]
import os
import sys

# Fetch big_vision repository if python doesn't know about it and install
# dependencies needed for this notebook.
if not os.path.exists("big_vision_repo"):
  !git clone --quiet --branch=main --depth=1 \
     https://github.com/google-research/big_vision big_vision_repo
#This is the solution

# Append big_vision code to python import path
if "big_vision_repo" not in sys.path:
  sys.path.append("big_vision_repo")

# Install missing dependencies. Assume jax~=0.4.25 with GPU available.
!pip install -q "overrides" "ml_collections" "einops~=0.7" "sentencepiece"

**Comment by oksidgy** [comment]
> git clone --quiet --branch=main --depth=1 https://github.com/google-research/big_vision big_vision
> export PYTHONPATH=$PYTHONPATH:~/<your_path_to_big_vision>/big_vision
