### ISSUE TITLE
ModuleNotFoundError: No module named 'big_vision'

### ISSUE THREAD

**Issue by sycamoreoak** [google-research/scenic#1075]
fresh venv on an up-to-date Ubuntu 22.04.4 LTS

following the README.md:
```
$ pip install .

$python scenic/main.py -- \
  --config=scenic/projects/baselines/configs/imagenet/imagenet_vit_config.py \
  --workdir=./
2024-06-11 20:31:14.693998: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "~/src/python/scenic/scenic/main.py", line 27, in <module>
    from scenic.train_lib import trainers
  File "~/src/python/scenic/env_scenic/lib/python3.10/site-packages/scenic/train_lib/trainers.py", line 18, in <module>
    from scenic.train_lib.transfer import transfer_trainer
  File "~/src/python/scenic/env_scenic/lib/python3.10/site-packages/scenic/train_lib/transfer/transfer_trainer.py", line 38, in <module>
    from scenic.train_lib import pretrain_utils
  File "~/src/python/scenic/env_scenic/lib/python3.10/site-packages/scenic/train_lib/pretrain_utils.py", line 23, in <module>
    from big_vision import utils
ModuleNotFoundError: No module named 'big_vision'
```

i'll go install big_vision but it would be nice if the jax ecosystem had a stronger JustWorks coefficient

**Comment by xiexie123** [comment]
+1

**Comment by ayushnangia** [comment]
just install the big_vision github

**Comment by salashhab** [comment]
`import os
import sys

#Fetch big_vision repository if python doesn't know about it and install

#dependencies needed for this notebook.
if not os.path.exists("big_vision_repo"):
  !git clone --quiet --branch=main --depth=1 https://github.com/google-research/big_vision big_vision_repo
  
#This is the solution
#Append big_vision code to python import path
if "big_vision_repo" not in sys.path:
  sys.path.append("big_vision_repo")

#Install missing dependencies. Assume jax~=0.4.25 with GPU available.
!pip install -q "overrides" "ml_collections" "einops~=0.7" "sentencepiece"`

**Comment by KyonP** [comment]
I can avoid the error this way, but I'm still encountering several other dependency errors.

`!PYTHONPATH="$(pwd):/path/to/big_vision/`

**Comment by czb7046** [comment]
install this https://github.com/google-research/big_vision

**Comment by jiaxi98** [comment]
How to install the big_vision repo? The command provides in their README does not install the repo, only the dependency. Currently, I am following @salashhab's method to add system path. Would be better if one can install big_vision. I open an issue in big_vision repo: https://github.com/google-research/big_vision/issues/175.
