### ISSUE TITLE
OWlVit:     KeyError: 'ln_2'

### ISSUE THREAD

**Issue by yangt1013** [google-research/scenic#1127]
Hi, author, I met some issues with evaluator stage.
When I training and testing as followings, there are some weird in model file.

Traceback (most recent call last):
  File "/home/yangt/miniconda3/envs/pytorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yangt/miniconda3/envs/pytorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/ssd1/yangt/FG-OVD/scenic/scenic/projects/owl_vit/evaluator.py", line 741, in <module>
    app.run(main)
  File "/home/yangt/.local/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/yangt/.local/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/ssd1/yangt/FG-OVD/scenic/scenic/projects/owl_vit/evaluator.py", line 698, in main
    predictions = get_predictions(
  File "/ssd1/yangt/FG-OVD/scenic/scenic/projects/owl_vit/evaluator.py", line 420, in get_predictions
    variables = module.load_variables(checkpoint_path=checkpoint_path)
  File "/ssd1/yangt/FG-OVD/scenic/scenic/projects/owl_vit/models.py", line 122, in load_variables
    params = _fix_old_checkpoints(params)
  File "/ssd1/yangt/FG-OVD/scenic/scenic/projects/owl_vit/models.py", line 73, in _fix_old_checkpoints
    params['backbone']['clip']['visual']['transformer'] = _fix_old_layernorm(
  File "/ssd1/yangt/FG-OVD/scenic/scenic/projects/owl_vit/models.py", line 49, in _fix_old_layernorm
    resblock['ln_1'] = resblock.pop('ln_2')
KeyError: 'ln_2'

How can I revise it?

**Comment by Torpedo2648** [comment]
The same question! Have you fixed it? #

**Comment by 1Fleeting-time** [comment]
> 同样的问题！你修好了吗？#

修改代码
