### ISSUE TITLE
AssertionError: Duplicate registrations for type 'experimentalOptimizer'`

### ISSUE THREAD

**Issue by hanhung** [google-research/scenic#213]
Hello, I am trying to import clip using scenic by using:
`from scenic.projects.baselines.clip import model as clip`
However, an error like this occured:
`tensorflow.python.framework.errors_impl.AlreadyExistsError: Another metric with the same name already exists.`
I have tried downgrading keras as suggested [here](https://stackoverflow.com/questions/58012741/error-importing-tensorflow-alreadyexistserror-another-metric-with-the-same-nam), however another error occurs:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rex/anaconda3/envs/jax/lib/python3.9/site-packages/scenic/projects/baselines/clip/model.py", line 12, in <module>
    from scenic.projects.baselines.clip import download
  File "/home/rex/anaconda3/envs/jax/lib/python3.9/site-packages/scenic/projects/baselines/clip/download.py", line 9, in <module>
    from tensorflow.io import gfile
  File "/home/rex/anaconda3/envs/jax/lib/python3.9/site-packages/tensorflow/__init__.py", line 473, in <module>
    keras._load()
  File "/home/rex/anaconda3/envs/jax/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/home/rex/anaconda3/envs/jax/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/rex/anaconda3/envs/jax/lib/python3.9/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/home/rex/anaconda3/envs/jax/lib/python3.9/site-packages/keras/models.py", line 20, in <module>
    from keras import metrics as metrics_module
  File "/home/rex/anaconda3/envs/jax/lib/python3.9/site-packages/keras/metrics/__init__.py", line 23, in <module>
    from keras.metrics.base_metric import Metric
  File "/home/rex/anaconda3/envs/jax/lib/python3.9/site-packages/keras/metrics/base_metric.py", line 25, in <module>
    from keras.engine import base_layer
  File "/home/rex/anaconda3/envs/jax/lib/python3.9/site-packages/keras/engine/base_layer.py", line 43, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/home/rex/anaconda3/envs/jax/lib/python3.9/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 20, in <module>
    from keras.optimizer_experimental import optimizer as optimizer_experimental
  File "/home/rex/anaconda3/envs/jax/lib/python3.9/site-packages/keras/optimizer_experimental/optimizer.py", line 649, in <module>
    tf.__internal__.saved_model.load.register_revived_type(
  File "/home/rex/anaconda3/envs/jax/lib/python3.9/site-packages/tensorflow/python/saved_model/revived_types.py", line 133, in register_revived_type
    raise AssertionError(f"Duplicate registrations for type '{identifier}'")
AssertionError: Duplicate registrations for type 'experimentalOptimizer'`

**Comment by hanhung** [comment]
Seems like a problem with the keras package. Removing the optimizer folder from the keras package in the anaconda environment fixed this ([following this](https://www.reddit.com/r/tensorflow/comments/srv3fe/weird_assertion_error_assertionerror_duplicate/)).
