### ISSUE TITLE
imagenet demo not working out of the box

### ISSUE THREAD

**Issue by brettkoonce** [google-research/scenic#460]
see also https://github.com/google/flax/issues/2403

flax 0.6 moved some things about, the resnet/vit demos will need to be updated:

`python3 scenic/main.py  --config=scenic/projects/baselines/configs/imagenet/imagenet_resnet_config.py  --workdir=/code/resnet-v3`
```

2022-08-19 01:19:21.743758: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
WARNING:absl:GlobalAsyncCheckpointManager is not imported correctly. Checkpointing of GlobalDeviceArrays will not be available.To use the feature, install tensorstore.
Traceback (most recent call last):
  File "/code/scenic/scenic/main.py", line 27, in <module>
    from scenic.train_lib import trainers
  File "/usr/local/lib/python3.9/dist-packages/scenic/train_lib/trainers.py", line 18, in <module>
    from scenic.train_lib.transfer import transfer_trainer
ModuleNotFoundError: No module named 'scenic.train_lib.transfer'
```

**Comment by gses82** [comment]
I have the same issue. Adding `scenic/train_lib/transfer/__init__.py` and reinstalling scenic solved my problem.

**Comment by brettkoonce** [comment]
closed the upstream bug!
