### ISSUE TITLE
OWL-ViT correct instructions to run it.

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [google-research/scenic#533]
Dear all,

I hope you are doing great. I am trying to run your code using the following docker file

```
FROM nvcr.io/nvidia/tensorflow:22.09-tf2-py3
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London
RUN apt update && apt install -y git software-properties-common
WORKDIR /workspace
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
RUN cd /workspace && git clone https://github.com/google-research/scenic.git &&\
    cd scenic &&\
    sed -i '/    "tf-models-official",/d' ./setup.py &&\
    python3 -m pip install -q . &&\
    python3 -m pip install -r scenic/projects/baselines/clip/requirements.txt &&\
    python3 -m pip install scikit-image &&\
    python3 -m pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

ENTRYPOINT [ "/bin/bash" ]

```

Then,

```
docker build -t owl-vit .
docker run --gpus all --ipc host --shm-size=64g --ulimit memlock=-1 --ulimit stack=67108864 -it -v $(pwd)/:/workspace owl-vit
```

I have a `demo.py` file

```python
import os

import jax
import matplotlib as mpl
from matplotlib import pyplot as plt
import numpy as np
from scenic.projects.owl_vit import models
from scenic.projects.owl_vit.configs import clip_l14 as config_module
from scenic.projects.owl_vit.notebooks import inference
# from scenic.projects.owl_vit.notebooks import interactive
# from scenic.projects.owl_vit.notebooks import plotting
from scipy.special import expit as sigmoid
import skimage
from skimage import io as skimage_io
from skimage import transform as skimage_transform
import tensorflow as tf

tf.config.experimental.set_visible_devices([], 'GPU')

config = config_module.get_config()
module = models.TextZeroShotDetectionModule(
    body_configs=config.model.body,
    normalize=config.model.normalize,
    box_bias=config.model.box_bias)
variables = module.load_variables(config.init_from.checkpoint_path)
model = inference.Model(config, module, variables)
model.warm_up()
```

If I try to run it I get the following error

```
WARNING:absl:GlobalAsyncCheckpointManager is not imported correctly. Checkpointing of GlobalDeviceArrays will not be available.To use the feature, install tensorstore.
2022-10-10 11:57:55.893917: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
100%|█████████████████████████████████████| 1.29M/1.29M [00:00<00:00, 23.0MiB/s]
2022-10-10 11:59:00.834105: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2130] Execution of replica 0 failed: INTERNAL: Failed to allocate 4194304 bytes for new constant
Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    model.warm_up()
  File "/usr/local/lib/python3.8/dist-packages/scenic/projects/owl_vit/notebooks/inference.py", line 54, in warm_up
    self.get_scores(image, query_embeddings, len(queries))
  File "/usr/local/lib/python3.8/dist-packages/scenic/projects/owl_vit/notebooks/inference.py", line 183, in get_scores
    image_features, _, _ = self.embed_image(image)
  File "/usr/local/lib/python3.8/dist-packages/scenic/projects/owl_vit/notebooks/numpy_cache.py", line 16, in wrapper
    return cached_wrapper(*hashable_args, **hashable_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/scenic/projects/owl_vit/notebooks/numpy_cache.py", line 22, in cached_wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/scenic/projects/owl_vit/notebooks/inference.py", line 89, in embed_image
    out = self._embed_image_jitted(image[None, ...])
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 604, in cache_miss
    out_flat = xla.xla_call(
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1959, in bind
    return call_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 1975, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 701, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 237, in _xla_call_impl
    return compiled_fun(*args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py", line 883, in _execute_compiled
    out_flat = compiled.execute(in_flat)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to allocate 4194304 bytes for new constant

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "demo.py", line 27, in <module>
    model.warm_up()
  File "/usr/local/lib/python3.8/dist-packages/scenic/projects/owl_vit/notebooks/inference.py", line 54, in warm_up
    self.get_scores(image, query_embeddings, len(queries))
  File "/usr/local/lib/python3.8/dist-packages/scenic/projects/owl_vit/notebooks/inference.py", line 183, in get_scores
    image_features, _, _ = self.embed_image(image)
  File "/usr/local/lib/python3.8/dist-packages/scenic/projects/owl_vit/notebooks/numpy_cache.py", line 16, in wrapper
    return cached_wrapper(*hashable_args, **hashable_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/scenic/projects/owl_vit/notebooks/numpy_cache.py", line 22, in cached_wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/scenic/projects/owl_vit/notebooks/inference.py", line 89, in embed_image
    out = self._embed_image_jitted(image[None, ...])
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to allocate 4194304 bytes for new constant
```

Thanks,

Francesco

**Comment by mjlm** [comment]
This looks like an "out of memory" error. How much memory does your GPU have? You could try to run on CPU by using a non-CUDA installation. It will be very slow, but it might be useful for debugging.

**Comment by FrancescoSaverioZuppichini** [comment]
Actually, the model failed to load on gpu and tries to run on cpu

**Comment by cpwan** [comment]
I have the same problem with the colab playground demo. It seems to be a problem with Jax's GPU pre-allocation.
Setting the environmental variable `XLA_PYTHON_CLIENT_PREALLOCATE=false` resolves the problem. See #646.
