### ISSUE TITLE
[OWL-ViT] Finetuning 'Could not find parameter named "scale"'

### ISSUE THREAD

**Issue by kdcd** [google-research/scenic#560]
Hello 

Thank you for the great work!  
I have tested evaluation, and training, but got exception on finetuning. 
It seems some inconsistency between clip weights in checkpoint and flax version.  Maybe you can provide pip freeze from the system where you have tested finetuning?

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/scenic/projects/owl_vit/main.py", line 47, in <module>
    app.run(main=main)
  File "/workspace/scenic/app.py", line 65, in run
    app.run(functools.partial(_run_main, main=main))
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/workspace/scenic/app.py", line 100, in _run_main
    main(rng=rng, config=FLAGS.config, workdir=FLAGS.workdir, writer=writer)
  File "/workspace/scenic/projects/owl_vit/main.py", line 37, in main
    trainer.train(
  File "/workspace/scenic/projects/owl_vit/trainer.py", line 388, in train
    train_state, t_metrics = train_step_pmapped(train_state, train_batch)
  File "/workspace/scenic/projects/owl_vit/trainer.py", line 114, in train_step
    grad, metrics = jax.vmap(grad_fn, 0)(inp)
  File "/workspace/scenic/projects/owl_vit/trainer.py", line 98, in grad_fn
    (_, metrics), grad = compute_gradient_fn(train_state.params)
  File "/workspace/scenic/projects/owl_vit/trainer.py", line 87, in loss_fn
    predictions = flax_model.apply(
  File "/workspace/scenic/projects/owl_vit/models.py", line 150, in __call__
    feature_map = self.image_embedder(inputs, train)
  File "/workspace/scenic/projects/owl_vit/models.py", line 109, in image_embedder
    image_features, _ = self._embedder(images=images, train=train)
  File "/workspace/scenic/projects/owl_vit/layers.py", line 172, in __call__
    img_emb, txt_emb = model(
  File "/workspace/scenic/projects/owl_vit/clip/layers.py", line 489, in __call__
    x = self.encode_image(image, normalize, deterministic=deterministic)
  File "/workspace/scenic/projects/owl_vit/clip/layers.py", line 466, in encode_image
    x = self.visual(image, deterministic=deterministic)[0]
  File "/workspace/scenic/projects/owl_vit/clip/layers.py", line 345, in __call__
    x = feature_map = Transformer(
  File "/workspace/scenic/projects/owl_vit/clip/layers.py", line 296, in __call__
    x = ResidualAttentionBlock(
  File "/workspace/scenic/projects/owl_vit/clip/layers.py", line 264, in __call__
    xn = LayerNorm(name='ln_2')(x)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/normalization.py", line 334, in __call__
    return _normalize(
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/normalization.py", line 142, in _normalize
    scale = mdl.param('scale', scale_init, reduced_feature_shape,
flax.errors.ScopeParamNotFoundError: Could not find parameter named "scale" in scope "/backbone/clip/visual/transformer/resblocks.0/ln_2". (https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.ScopeParamNotFoundError)

Mine pip freeze 

[pip_freeze.txt](https://github.com/google-research/scenic/files/9891560/pip_freeze.txt)

**Comment by ronhag** [comment]
Found the same issue. 

Not sure if this is the cause, but in this line https://github.com/google-research/scenic/blob/main/scenic/projects/owl_vit/trainer.py#L271 the model keys are changed from `ln_1` and `ln_2` to `ln_0`  and `ln_1`. @mjlm do you think this could the the reason? I'm not well-versed in flax yet, so not sure what's going on behind the scenes when we do `model.flax_model.bind({}).load(...`

**Comment by ronhag** [comment]
Hi there! @mjlm I'm unfortunately still facing the same issue that the parameter `scale` was not found. Any ideas why this could be the case?

**Comment by akornilo** [comment]
Hello,
I just started working with this codebase and am seeing this error when trying to finetune.
Has anyone been able to come up with a solution?

**Comment by AlexeyG** [comment]
Please try again after #651 is in.
