### ISSUE TITLE
ModuleNotFoundError: No module named 'official'

### ISSUE THREAD

**Issue by parhameftekhar** [google-research/scenic#592]
I'm trying to train a mbt model. However, I got the following error:

Traceback (most recent call last):
  File "/home/eftekhar/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/eftekhar/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/eftekhar/models/scenic/scenic/projects/mbt/main.py", line 47, in <module>
    app.run(main=main)
  File "/home/eftekhar/models/scenic/scenic/app.py", line 65, in run
    app.run(functools.partial(_run_main, main=main))
  File "/home/eftekhar/anaconda3/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/eftekhar/anaconda3/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/eftekhar/models/scenic/scenic/app.py", line 100, in _run_main
    main(rng=rng, config=FLAGS.config, workdir=FLAGS.workdir, writer=writer)
  File "/home/eftekhar/models/scenic/scenic/projects/mbt/main.py", line 34, in main
    dataset = train_utils.get_dataset(
  File "/home/eftekhar/models/scenic/scenic/train_lib_deprecated/train_utils.py", line 280, in get_dataset
    dataset_builder = datasets.get_dataset(dataset_name)
  File "/home/eftekhar/models/scenic/scenic/dataset_lib/datasets.py", line 144, in get_dataset
    return DatasetRegistry.get(dataset_name)
  File "/home/eftekhar/models/scenic/scenic/dataset_lib/datasets.py", line 107, in get
    importlib.import_module(module)
  File "/home/eftekhar/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/eftekhar/models/scenic/scenic/projects/vivit/data/video_tfrecord_dataset.py", line 18, in <module>
    from scenic.dataset_lib import video_ops
  File "/home/eftekhar/models/scenic/scenic/dataset_lib/video_ops.py", line 35, in <module>
    from official.vision.image_classification import augment
ModuleNotFoundError: No module named 'official'

**Comment by Claire874** [comment]
I encoutered the same problem.

**Comment by satojkovic** [comment]
@parhameftekhar @Claire874 
I ran into the same problem. So I did the following to solve the problem.

1. ```pip install tf-models-official```
2. Modify the import -> ```from official.legacy.image_classification import augment```

Please try it out.

**Comment by parhameftekhar** [comment]
@satojkovic Thanks solved the issue. However, a new one came up. I close this issue.

**Comment by parhameftekhar** [comment]
@satojkovic 
were you able to run the code successfully? if so could you share your config file?

**Comment by Elaheh-Motamedi** [comment]
@parhameftekhar 
Hi, Could you please share your config file? I have some problems with optimizer.
