### ISSUE TITLE
[vivit for ssv2] Inconsistent shapes between value and initializer for parameter "pos_embedding" in "/SpatialTransformer/posembed_input": (1, 197, 1024), (1, 257, 1024).

### ISSUE THREAD

**Issue by StonePanda** [google-research/scenic#598]
Dear All, thank you for your great work!
I am trying to train vivit on ssv2, here is the command:
`python -m scenic.projects.vivit.main --config=scenic/scenic/projects/vivit/configs/something_something_v2/vivit_large_factorised_encoder.py --workdir=myworkdirpath/`
and here is the Initialisation config:
```
  config.init_from = ml_collections.ConfigDict()
  # Use a pretrained Kinetics checkpoint, or ImageNet checkpoint
  config.init_from.checkpoint_path = 'ViT_L_16_ImageNet21k'
  config.init_from.checkpoint_format = 'scenic'
  config.init_from.model_config = ml_collections.ConfigDict()
  config.init_from.model_config.model = ml_collections.ConfigDict()
  config.init_from.model_config.model.classifier = 'token'  # Specify if this is 'token' or 'gap'.  pylint: disable=line-too-long
  config.init_from.checkpoint_path = None
  config.init_from.restore_positional_embedding = True
  config.init_from.restore_input_embedding = True
  config.init_from.positional_embed_size_change = 'resize'
```
I download the ImageNet Checkpoint from [(https://github.com/google-research/scenic/tree/main/scenic/projects/baselines)](https://github.com/google-research/scenic/tree/main/scenic/projects/baselines)
And there is a Kinetics checkpoint (ViViT-L/16x2 FE trained on Kinetics400 downloaded from https://github.com/google-research/scenic/tree/main/scenic/projects/vivit) in workdir.
The positional embedding shape should be the same (1,257,1024), but I got this error:
```
I1123 03:07:29.712457 140411719832704 checkpoints.py:429] Restoring checkpoint from myworkdirpath/checkpoint_vivit_L_16*2_FE_kinetics400
I1123 03:07:37.677523 140411719832704 trainer.py:204] Starting training loop at step 100681.
I1123 03:07:39.357655 140411719832704 model.py:115] Using central frame initializer for input embedding
Traceback (most recent call last):
  File "/home/scenic/scenic/projects/vivit/main.py", line 44, in <module>
    app.run(main=main)
  File "/home/scenic/scenic/app.py", line 65, in run
    app.run(functools.partial(_run_main, main=main))
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/scenic/scenic/app.py", line 100, in _run_main
    main(rng=rng, config=FLAGS.config, workdir=FLAGS.workdir, writer=writer)
  File "/home/scenic/scenic/projects/vivit/main.py", line 34, in main
    trainer(
  File "/home/scenic/scenic/projects/vivit/trainer.py", line 234, in train
    train_state, t_metrics, lr = train_step_pmapped(train_state, train_batch)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/_src/api.py", line 2248, in cache_miss
    execute = pxla.xla_pmap_impl_lazy(fun_, *tracers, **params)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 974, in xla_pmap_impl_lazy
    compiled_fun, fingerprint = parallel_callable(
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/linear_util.py", line 300, in memoized_fun
    ans = call(fun, *args)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 1225, in parallel_callable
    pmap_computation = lower_parallel_callable(
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 1393, in lower_parallel_callable
    jaxpr, consts, replicas, parts, shards = stage_parallel_callable(
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/interpreters/pxla.py", line 1300, in stage_parallel_callable
    jaxpr, out_sharded_avals, consts = pe.trace_to_jaxpr_final(
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2069, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 2002, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers_)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/scenic/scenic/projects/vivit/train_utils.py", line 121, in train_step
    logits)), grad = compute_gradient_fn(train_state.optimizer.target)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/_src/api.py", line 1167, in value_and_grad_f
    ans, vjp_py, aux = _vjp(
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/_src/api.py", line 2654, in _vjp
    out_primal, out_vjp, aux = ad.vjp(
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/interpreters/ad.py", line 137, in vjp
    out_primals, pvals, jaxpr, consts, aux = linearize(traceable, *primals, has_aux=True)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/interpreters/ad.py", line 124, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/interpreters/partial_eval.py", line 767, in trace_to_jaxpr_nounits
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/scenic/scenic/projects/vivit/train_utils.py", line 104, in training_loss_fn
    logits, new_model_state = flax_model.apply(
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/linen/module.py", line 1176, in apply
    return apply(
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/core/scope.py", line 864, in wrapper
    y = fn(root, *args, **kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/linen/module.py", line 1579, in scope_fn
    return fn(module.clone(parent=scope), *args, **kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/linen/transforms.py", line 1320, in wrapped_fn
    return jax.named_call(class_fn, name=full_name)(self, *args, **kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/linen/module.py", line 353, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/linen/module.py", line 652, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/home/scenic/scenic/projects/vivit/model.py", line 583, in __call__
    x = jax.vmap(
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/_src/api.py", line 1680, in vmap_f
    out_flat = batching.batch(
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/scenic/scenic/projects/vivit/model.py", line 563, in vit_body
    x = Encoder(
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/linen/transforms.py", line 1320, in wrapped_fn
    return jax.named_call(class_fn, name=full_name)(self, *args, **kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/linen/module.py", line 353, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/linen/module.py", line 652, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/home/scenic/scenic/projects/vivit/model.py", line 363, in __call__
    x = vit.AddPositionEmbs(
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/linen/transforms.py", line 1320, in wrapped_fn
    return jax.named_call(class_fn, name=full_name)(self, *args, **kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/linen/module.py", line 353, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/linen/module.py", line 652, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/home/scenic/scenic/projects/baselines/vit.py", line 40, in __call__
    pe = self.param('pos_embedding', self.posemb_init, pos_emb_shape,
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/linen/module.py", line 990, in param
    v = self.scope.param(name, init_fn, *init_args)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/flax/core/scope.py", line 767, in param
    raise errors.ScopeParamShapeError(name, self.path_text,
jax._src.traceback_util.UnfilteredStackTrace: flax.errors.ScopeParamShapeError: Inconsistent shapes between value and initializer for parameter "pos_embedding" in "/SpatialTransformer/posembed_input": (1, 197, 1024), (1, 257, 1024). (https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.ScopeParamShapeError)

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/anaconda3/envs/scenic/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/anaconda3/envs/scenic/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/scenic/scenic/projects/vivit/main.py", line 44, in <module>
    app.run(main=main)
  File "/home/scenic/scenic/app.py", line 65, in run
    app.run(functools.partial(_run_main, main=main))
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/scenic/scenic/app.py", line 100, in _run_main
    main(rng=rng, config=FLAGS.config, workdir=FLAGS.workdir, writer=writer)
  File "/home/scenic/scenic/projects/vivit/main.py", line 34, in main
    trainer(
  File "/home/scenic/scenic/projects/vivit/trainer.py", line 234, in train
    train_state, t_metrics, lr = train_step_pmapped(train_state, train_batch)
  File "/home/scenic/scenic/projects/vivit/train_utils.py", line 121, in train_step
    logits)), grad = compute_gradient_fn(train_state.optimizer.target)
  File "/home/scenic/scenic/projects/vivit/train_utils.py", line 104, in training_loss_fn
    logits, new_model_state = flax_model.apply(
  File "/home/anaconda3/envs/scenic/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/scenic/scenic/projects/vivit/model.py", line 583, in __call__
    x = jax.vmap(
  File "/home/scenic/scenic/projects/vivit/model.py", line 563, in vit_body
    x = Encoder(
  File "/home/anaconda3/envs/scenic/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/scenic/scenic/projects/vivit/model.py", line 363, in __call__
    x = vit.AddPositionEmbs(
  File "/home/anaconda3/envs/scenic/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/scenic/scenic/projects/baselines/vit.py", line 40, in __call__
    pe = self.param('pos_embedding', self.posemb_init, pos_emb_shape,
flax.errors.ScopeParamShapeError: Inconsistent shapes between value and initializer for parameter "pos_embedding" in "/SpatialTransformer/posembed_input": (1, 197, 1024), (1, 257, 1024). (https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.ScopeParamShapeError)
```
I have no idea how to resolve it. Thank you for any suggestion!

**Comment by StonePanda** [comment]
I am also confused the checkpoint needed in workdir. If there is no checkpoint, this error happens:
```
I1123 10:25:44.083591 140304616264832 checkpoints.py:425] Found no checkpoint files in myworkdirpath with prefix checkpoint_
Traceback (most recent call last):
  File "/home/anaconda3/envs/scenic/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/anaconda3/envs/scenic/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/scenic/scenic/projects/vivit/main.py", line 44, in <module>
    app.run(main=main)
  File "/home/scenic/scenic/app.py", line 65, in run
    app.run(functools.partial(_run_main, main=main))
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/scenic/scenic/app.py", line 100, in _run_main
    main(rng=rng, config=FLAGS.config, workdir=FLAGS.workdir, writer=writer)
  File "/home/scenic/scenic/projects/vivit/main.py", line 34, in main
    trainer(
  File "/home/scenic/scenic/projects/vivit/trainer.py", line 96, in train
    restored_train_state = pretrain_utils.restore_pretrained_checkpoint(
  File "/home/scenic/scenic/train_lib_deprecated/pretrain_utils.py", line 198, in restore_pretrained_checkpoint
    glob_path = os.path.join(checkpoint_path, 'checkpoint_*')
  File "/home/anaconda3/envs/scenic/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
I1123 10:25:44.083591 140304616264832 checkpoints.py:425] Found no checkpoint files in myworkdirpath with prefix checkpoint_
Traceback (most recent call last):
  File "/home/anaconda3/envs/scenic/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/anaconda3/envs/scenic/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/scenic/scenic/projects/vivit/main.py", line 44, in <module>
    app.run(main=main)
  File "/home/scenic/scenic/app.py", line 65, in run
    app.run(functools.partial(_run_main, main=main))
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/anaconda3/envs/scenic/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/scenic/scenic/app.py", line 100, in _run_main
    main(rng=rng, config=FLAGS.config, workdir=FLAGS.workdir, writer=writer)
  File "/home/scenic/scenic/projects/vivit/main.py", line 34, in main
    trainer(
  File "/home/scenic/scenic/projects/vivit/trainer.py", line 96, in train
    restored_train_state = pretrain_utils.restore_pretrained_checkpoint(
  File "/home/scenic/scenic/train_lib_deprecated/pretrain_utils.py", line 198, in restore_pretrained_checkpoint
    glob_path = os.path.join(checkpoint_path, 'checkpoint_*')
  File "/home/anaconda3/envs/scenic/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
