### ISSUE TITLE
ModuleNotFoundError: No module named 'scenic.train_lib_deprecated'

### ISSUE THREAD

**Issue by jena-shreyas** [google-research/scenic#826]
I was trying to set up `vid2seq` for evaluation, but on running the command : 

```
python -m scenic.projects.vid2seq.main \
    --config=scenic/projects/vid2seq/configs/youcook2.py \
    `--workdir=vid2seq_base/
```

I obtained the following error stack : 

```
2023-06-28 01:47:42.571340: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/usr/local/envs/vid2seq/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/envs/vid2seq/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/content/BTP/scenic/scenic/projects/vid2seq/main.py", line 13, in <module>
    from scenic.projects.vid2seq import trainer
  File "/content/BTP/scenic/scenic/projects/vid2seq/trainer.py", line 28, in <module>
    from scenic.projects.vid2seq import load_utils
  File "/content/BTP/scenic/scenic/projects/vid2seq/load_utils.py", line 16, in <module>
    from scenic.train_lib_deprecated.pretrain_utils import get_params_and_model_state_dict
ModuleNotFoundError: No module named 'scenic.train_lib_deprecated'
```

Apparently, the main `scenic` repo has dropped the folder `scenic/train_lib_deprecated` as well as all its functionalities - but `load_utils.py` in `vid2seq` still uses it - any way out ?

**Comment by whatiskeptiname** [comment]
I am facing the same problem, have you found any solution?

**Comment by JeremyWongJW** [comment]
The 'train_lib_deprecated' has been removed, but I find the removed files here **https://github.com/google-research/scenic/pull/794/files**. Maybe we could solve the issue by recreating these files somewhere till the official solution come out.

**Comment by vishaal27** [comment]
Were you able to find a work-around that runs? @jena-shreyas

**Comment by antoyang** [comment]
One turnaround could consist of using the Vid2Seq PyTorch implementation (with a few differences described in the readme) included here: https://github.com/antoyang/VidChapters.
